version: '3.8'

services:
  app:
    build: .
    container_name: laayoune_votes_app
    ports:
      - "4000:4000"
    volumes:
      - ./depouillement_laayoune.db:/app/depouillement_laayoune.db
    restart: always
